### PR TITLE
fix: updated pg-meta api

### LINKED ISSUE #38: Could not connect to local Supabase project
# Bug report

## Describe the bug

i installed supabase cli by brew then i used "supabase start" but i had this issue on vscode extension "Could not connect to local Supabase project. Make sure you've run 'supabase start'!,"

## To Reproduce

1. brew install supabase/tap/supabase
2. supabase start
3. install vscode supabase extension

## Screenshots

Image

## System information

- OS: [e.g. macOS Sequora 15.1 ]
- Browser (if applies) [chrome]
- Version of supabase-js: [2.15.8]
- Version of Node.js: [21.7.2]

### PR DESCRIPTION
**Pull request by anas-araid**
fixes #38

### CODE REVIEW

**Comment by steinerd** [comment]
I've been running a self-compiled version of this VSIX for about a week now... no issues to report. 

I would _**love**_ to see this merged into the official-stable channel.

**Comment by drago1520** [comment]
Please fix the extension. It does not work at all

**Comment by drago1520** [comment]
Thank you for the pull request @anas-araid !

**Comment by zouhirdev** [comment]
any updates on this or at least a compiled version of the fix i dont know how to compile it

**Comment by btelles** [comment]
Han and Greg, any chance either of you can take a quick look at this? The extension non-functional without this fix.

File: src/features/database/classes/supabase-api.ts [hunk 1]
```diff
@@ -100,11 +103,11 @@ export class SupabaseApi {
 
   async getDatabaseFunctions(): Promise<DatabaseFunction[]> {
     const endpoint = `${this.baseUrl}:${Ports.PG_META}` + Endpoint.DB_FUNCTIONS;
-    const [err, res] = await to(axios.get(endpoint));
-
-    if (err) {
-      vscode.window.showErrorMessage(err.message);
```
Comment (btelles) [inline src/features/database/classes/supabase-api.ts:106]: Any particular reason for removing this?

**Review by Hallidayo — APPROVED** [review]
Tested locally and I can see my local supabase instance
